name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Set variables
      shell: bash
      run:  |
        echo "GIT_COMMIT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
        echo "DOCKER_TAG=ci-${GIT_COMMIT}" >> $GITHUB_ENV

    - name: Build docker image for tests
      run: DOCKER_TAG=${{ env.DOCKER_TAG }} DOCKER_TARGET=test make build-image

    - name: test application
      run: DOCKER_TAG=${{ env.DOCKER_TAG }} make test-ci
